### ISSUE TITLE
The program 'autotest' is currently not installed.

### ISSUE THREAD

**Issue by marko-avlijas** [rspec/rspec-autotest#26]
It seems documentation has a piece missing to make it work.

This is part of my Gemfile:

    gem 'rspec', ">=3.0"
    gem 'rspec-autotest'

After I run `bundle` I got this message in green:
`Installing rspec-autotest 1.0.0`

Yet when I ran `autotest` I get:

    The program 'autotest' is currently not installed. You can install it by typing:
    sudo apt install ruby-zentest

`.rspec` file does exist:

    $ cat .rspec 
    --color
    --require spec_helper

Do I really need ruby-zentest?  I have no idea what's that. By reading documentation I thought I could just type `autotest` and everything would work.

How to make it work?

**Comment by JonRowe** [comment]
`rspec-autotest` was extracted as an extension gem for adding helpers for the autotest gems, there are two gems providing this currently, `autotest-standalone` and `zentest`, I guess the documentation is a bit lax on that, I'll work something up.

**Comment by marko-avlijas** [comment]
Well I googled for `rspec autotest` and I think  this  was first result. Perhaps you can expect more people like me.

So I need to put only `gem 'autotest-standalone'` or `gem 'zentest'` in my Gemfile and delete `gem rspec-autotest`?

**Comment by JonRowe** [comment]
autotest is outdated, guard is more commonly used these days.

**Comment by marko-avlijas** [comment]
Thank you.
